spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          # The cors configuration to allow frontend developers cross origin request via this api gateway
          '[/**]':
            allowedOrigins:
              - "http://localhost:8081"
              - "http://127.0.0.1:8081"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: sso
          uri: ${app.routes.sso.uri}
          predicates:
            - Path=/api/sso/userinfo
          filters:
            - RewritePath=/api/sso/userinfo, /auth/realms/${spring.realm}/protocol/openid-connect/userinfo
        - id: backend
          uri: ${app.routes.backend.uri}
          predicates:
            - Path=/api/clientid-backend-service/**
          filters:
            - RewritePath=/api/clientid-backend-service/(?<urlsegments>.*), /$\{urlsegments}
            - RemoveResponseHeader=WWW-Authenticate