GET http://localhost:39146/actuator/info

###

GET http://localhost:39146/actuator/health

###

GET http://localhost:39146/actuator/health/liveness

###

GET http://localhost:39146/actuator/health/readiness

###

GET http://localhost:39146/actuator/metrics