GET http://localhost:39146/graphql

### GraphQL Tasks
GRAPHQL http://localhost:39146/graphql

query {
    getPersons {
        id
        firstname
        lastname
        email
    }
}

### GraphQL Persons with Tasks
GRAPHQL http://localhost:39146/graphql

query {
    getPersons {
        id
        firstname
        lastname
        email
        tasks {
            id
            title
            description
        }
    }
}