### Get all Tasks
GET http://localhost:39146/tasks


### Create Task with Creator
POST http://localhost:39146/tasks
Content-Type: application/json

{
  "title": "Task with Creator",
  "description": "Just another task. But this one has a linked creator",
  "dueDate": null,
  "creatorId": "b75a10fd-9476-4fab-a410-0351bb5dd68d"
}