GET {{ backend }}/graphql

### get healthstatus
GET {{ backend }}/actuator/health

### GraphQL Tasks
GRAPHQL {{ backend }}/graphql
Authorization: {{ token_type }} {{ auth_token }}

query {
    getTasks {
        id
        title
        dueDate
        creatorId
        creator {
            email
            id
        }
        assigneeId
        assignee {
            id
            email
            firstname
            lastname
        }
    }
}