# Use root/example as user/password credentials
version: '3.1'

services:

  oracledb-xe:
    image:  container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - 1521:1521
    environment:
      ORACLE_PWD: secret
  # SQL> CREATE USER pp IDENTIFIED BY ppsecret QUOTA UNLIMITED ON USERS;
  # SQL> GRANT CONNECT, RESOURCE TO pp;

  gvenzl-oracledb-xe:
    image: gvenzl/oracle-xe
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: secret
      APP_USER: pp
      APP_USER_PASSWORD: ppsecret

  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: example-user
      MARIADB_PASSWORD: my_cool_secret
      MARIADB_DATABASE: exmple-database
      MARIADB_ROOT_PASSWORD: my-secret-pw
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: todo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8181:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/