# Use root/example as user/password credentials
version: '3.1'

services:

  oracledb-xe:
    image:  container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - 1521:1521
    environment:
      ORACLE_PWD: secret
  # sqlplus sys/secret@XEPDB1 as sysdba
  # SQL> CREATE USER todoapp IDENTIFIED BY todosecret QUOTA UNLIMITED ON USERS;
  # SQL> GRANT CONNECT, RESOURCE TO todoapp;

  gvenzl-oracledb-xe:
    image: gvenzl/oracle-xe
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: secret
      APP_USER: pp
      APP_USER_PASSWORD: ppsecret

  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: example-user
      MARIADB_PASSWORD: my_cool_secret
      MARIADB_DATABASE: exmple-database
      MARIADB_ROOT_PASSWORD: my-secret-pw
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: todo

  mongo-express:
    image: mongo-express
    ports:
      - 8181:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  test-postgres:
    image: postgres:16.1-alpine3.18
    container_name: todo-app-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    networks:
      postgres:

  # Keycloak (SSO)
  test-keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: test-keycloak
    command:
      - start-dev --http-relative-path /auth
    depends_on:
      - test-postgres-keycloak
    ports:
      - 8100:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: change_me
      KC_HOSTNAME_STRICT: false
      db: postgress
      features: token-exchange
      db-url: jdbc:postgresql://postgres-keycloak:5432/keycloak
      db-username: keycloak-user
      db-password: keycloak-secret
    networks:
      - keycloak

  test-init-keycloak:
    image: klg71/keycloakmigration
    depends_on:
      - test-keycloak
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: change_me
      BASEURL: http://test-keycloak:8080/auth # uses internal docker network to access the keycloak via its back channel port
      WAIT_FOR_KEYCLOAK: 'true'
      KEYCLOAK_CHANGELOG: /migration/keycloak-changelog.yml
    volumes:
      - './keycloak/migration:/migration'
    networks:
      - keycloak

  test-postgres-keycloak:
    image: postgres:13.2
    container_name: test-postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak-user
      POSTGRES_PASSWORD: keycloak-secret
    networks:
      - keycloak
      - postgres

  # Tools
  postgres-pg-admin:
    image: dpage/pgadmin4:7.8
    container_name: todo-app-pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@a.de
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8101:80
    networks:
      - postgres

networks:
  keycloak:
  postgres: