spring:
  # Spring JPA
  h2.console.enabled: true
  datasource:
    username: example-user
    password: my_cool_secret
    url: jdbc:mariadb://localhost:3306/exmple-database
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: false
  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # Logging for database operation
    show-sql: true
    properties:
      hibernate:
        format_sql: true