server:
  port: 39146
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://ssodev.muenchen.de/auth/realms/${realm}/protocol/openid-connect/certs


# Define the local keycloak realm here
realm: <YOUR_LOCAL_REALM>

security:
  # possible values: none, all, changing (With changing, only changing requests such as POST, PUT, DELETE are logged)
  logging.requests: all
  oauth2:
    resource.user-info-uri: https://ssodev.muenchen.de/auth/realms/${realm}/protocol/openid-connect/userinfo
