spring:
  jpa:
    database: postgresql
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    username: todo
    password: todo
    url: jdbc:postgresql://localhost/postgres
  flyway:
    enabled: true