spring:
  jpa:
    database: oracle
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    username: todoapp
    password: todosecret
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
  flyway:
    enabled: true