spring:
  flyway:
    enabled: true
    locations:
      - classpath:db/migrations/{vendor}
  jpa:
    hibernate:
      ddl-auto: validate
    # Logging for database operation
    show-sql: true
    properties:
      hibernate:
        format_sql: true