name: callable build gh release from tag
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
        description: 'tag that is used for build'
      service:
        required: true
        type: string
        description: 'name of service to use'

env:
  REGISTRY: ghcr.io

jobs:
  publish-ghcr-image:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          cache: 'maven'
          cache-dependency-path: '${{ inputs.service }}/pom.xml'
          java-version: '17'
          distribution: 'temurin'

      - name: build jar without tests
        run: mvn -B -ntp -DskipTests package -f ${{ inputs.service }}/pom.xml

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.getTagNameParts.outputs.service }}/target/*.jar
          draft: false
          prerelease: false
          generate_release_notes: false