name: build gh release from tag

on:
  push:
    tags:
      - "*/v*"

jobs:
  get-service-from-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2.1.3
        id: tagName
        with:
          tagRegex: (?<service>.*)\/v(?<version>.*)" #example: backend/v1.2.3
      - name: show-service
        env:
          ghRef: ${{ github.ref }}
          service: ${{ steps.tagName.outputs.service }}
          version: ${{ steps.tagName.outputs.version }}
          tagFromAction: ${{ steps.tagName.outputs.tag }}
        run: |
          echo "Ref: $ghRef"
          echo "Service: $service"
          echo "Version: $version"
          echo "tagFromAction: $tagFromAction"