name: build ghcr image

on:
  workflow_dispatch:
    inputs:
      ref:
        required: false
        description: 'tag/branch that is used for build'
        default: ''
      service:
        required: true
        description: 'name of service to use'
      image-name:
        required: false
        default: ''
        description: 'optional explicit image name'

jobs:
  build-ghcr-image:
    permissions:
      packages: write
    uses:
      ./.github/workflows/callable-create-ghcr-image-from-tag.yml
    with:
      tag: ${{ github.event.inputs.ref }}
      service: ${{ github.event.inputs.service }}
      image-name: ${{ github.event.inputs.image-name }}