name: dispatch maven deploy

on:
  workflow_dispatch:
    inputs:
      pom-dir:
        required: true
        type: choice
        description: service to build (backend, frontend, ...)
        options:
          - backend
          - backend-rest-api
          - frontend

jobs:
  mvn-deploy:
    permissions:
      packages: write
    uses:
      ./.github/workflows/callable-run-mvn-deploy.yml
    with:
      pom-dir: ${{ github.event.inputs.pom-dir }}