name: build maven release

on:
  workflow_dispatch:
    inputs:
      release-version:
        required: true
        description: release version
      development-version:
        required: true
        description: next development version
      service:
        required: true
        description: service to build (backend, frontend, ...)

jobs:
  prepare-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Java Maven release
        uses: qcastel/github-actions-maven-release@v1.12.41
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
        with:
          ssh-private-key: ${{ secrets.DEYPLOY_KEY_2 }}
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip -Dtag=${{ github.event.inputs.service }}/v${{ github.event.inputs.release-version }}"
          skip-perform: true
          maven-development-version-number: ${{ github.event.inputs.development-version }}
          maven-release-version-number: ${{ github.event.inputs.release-version }}
          release-branch-name: try-github-action-for-release
          maven-project-folder: ${{ github.event.inputs.service }}

#  build-gh-release:
#    permissions:
#      contents: write
#    needs:
#      - prepare-release
#    uses:
#      ./.github/workflows/callable-create-release-from-tag.yml
#    with:
#      tag: ${{ github.event.inputs.service }}/v${{ github.event.inputs.release-version }}
#      service: ${{ github.event.inputs.service }}
#
#  build-ghcr-image:
#    permissions:
#      packages: write
#    needs:
#      - prepare-release
#    uses:
#      ./.github/workflows/callable-create-ghcr-image-from-tag.yml
#    with:
#      tag: ${{ github.event.inputs.service }}/v${{ github.event.inputs.release-version }}
#      service: ${{ github.event.inputs.service }}