name: build ghcr image

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        description: 'tag that is used for build'
      service:
        required: true
        description: 'name of service to use'

jobs:
  build-ghcr-image:
    permissions:
      packages: write
    uses:
      ./.github/workflows/callable-create-ghcr-image-from-tag.yml
    with:
      tag: ${{ github.event.inputs.ref }}
      service: ${{ github.event.inputs.service }}