name: Lokaler Merge Workflow

on:
#  push:
#    paths:
#      - 'backend/**'
  pull_request:

jobs:
  merge_locally:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge PR into target branch locally
        env:
          TARGET_BRANCH: ${{ github.base_ref }}
        run: git merge ${{ TARGET_BRANCH }}
          

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run local tests
        run: mvn --batch-mode --update-snapshots --no-transfer-progress -f backend/pom.xml verify