name: verify frontend main push

on:
  push:
    branches:
      - 'main'
    paths:
      - 'frontend/**'

jobs:
  merge_locally:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: mvn verify
        run: mvn --batch-mode --update-snapshots --no-transfer-progress -f frontend/pom.xml verify