name: verify backend main push

on:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/**'
      - '.github/workflows/push_main_backend.yml'

jobs:
  checkout_and_verify:
    uses:
      ./.github/workflows/callable-run-mvn-verify.yml
    with:
      pom-dir: 'backend'

  publish-ghcr-image:
    uses:
      ./.github/workflows/callable-create-ghcr-image-from-tag.yml
    with:
      service: 'backend'