name: Trigger Publish
on:
  workflow_dispatch:
    inputs:
      project-dir:
        default: ''
        required: true
        type: string
        description: 'was ist das projekt directory'

jobs:
  publish-package:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reuse-release-workflow.yml
    with:
      project-dir: ${{ github.event.inputs.project-dir }}