name: Publish
on:
  workflow_call:
    inputs:
      project-dir:
        required: true
        type: string
        description: 'was ist das projekt directory'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-${{ inputs.project-dir }}

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          cache: "maven"
          java-version: '17'
          distribution: 'temurin'

      - name: Publish package
        run: mvn --batch-mode -f ${{ inputs.project-dir }}/pom.xml deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=match,pattern=(.*)-v(.*),group=1
            type=raw,value=latest-dev

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.project-dir }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}